export const FETCH_OPENING_HOURS = 'FETCH_OPENING_HOURS';

export const STORE_OPENING_HOURS = 'STORE_OPENING_HOURS';

export const UPDATE_OPENING_HOURS = 'UPDATE_OPENING_HOURS';

export const STORE_ORDER = 'STORE_ORDER';

export const FETCH_NEW_ORDERS = 'FETCH_NEW_ORDERS';

export const FETCH_NEW_ORDERS_SUCCESS = 'FETCH_NEW_ORDERS_SUCCESS';

export const FETCH_NEW_ORDERS_FAILURE = 'FETCH_NEW_ORDERS_FAILURE';

export const SET_ORDERS_SEARCH_TIME_FROM = 'SET_ORDERS_SEARCH_TIME_FROM';

export const SET_ORDERS_SEARCH_TIME_TO = 'SET_ORDERS_SEARCH_TIME_TO';

export const FETCH_ORDERS_LIST = 'FETCH_ORDERS_LIST';

export const FETCH_ORDERS_LIST_SUCCESS = 'FETCH_ORDERS_LIST_SUCCESS';

export const SET_LOADED_TO_FALSE = 'SET_LOADED_TO_FALSE';

export const products = {
    STORE_PRODUCTS: 'STORE_PRODUCTS',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    STORE_NEXT_PAGE: 'STORE_PRODUCTS_NEXT_PAGE',
    SET_LOAD_MORE_FALSE:'SET_PRODUCTS_LOAD_MORE'

};

export const productsMenu = {
    DELETE_PRODUCT_MENU: 'DELETE_PRODUCT_MENU',
    STORE_PRODUCTS_MENU: 'STORE_PRODUCTS_MENU',
};

export const opening_hours = {
    STORE_OPENING_HOURS: 'STORE_OPENING_HOURS',
    UPDATE_OPENING_HOURS: 'UPDATE_OPENING_HOURS'
};

export const order_list = {
    CHANGE_SEARCH_FIELD:'CHANGE_SEARCH_FIELD',
    STORE_ORDERS_LIST: 'STORE_ORDERS_LIST',
    SET_SEARCH_TIME_FROM: 'SET_SEARCH_TIME_FROM',
    SET_SEARCH_TIME_TO: 'SET_SEARCH_TIME_TO',
    SET_SEARCH_STATUS: 'SET_SEARCH_STATUS',
    SET_LOADED_TO_FALSE: 'SET_LOADED_TO_FALSE',
    STORE_NEXT_PAGE: 'STORE_ORDERS_LIST_NEXT_PAGE',
    SET_LOAD_MORE_FALSE:'SET_ORDERS_LIST_LOAD_MORE'
};

export const notifications = {
    STORE_NOTIFICATIONS: 'STORE_NOTIFICATIONS',
    REFRESH_NOTIFICATIONS: 'REFRESH_NOTIFICATIONS'
};

export const print_modal = {
    OPEN_PRINT_MODAL: 'OPEN_PRINT_MODAL',
    CLOSE_PRINT_MODAL: 'CLOSE_PRINT_MODAL'
}